image: zazukoians/node-java-jena
before_script:
  - scripts/bootstrap.sh
  - npm install


# stages
stages:
- fetch
- convert
- staging
- validate
- post

# jobs

fetch_incidents_job:
  stage: fetch
  script:
    - npm run fetch-incidents
  artifacts:
    paths:
      - input/incidents.csv
    expire_in: 30 minutes

fetch_sap_job:
  stage: fetch
  script:
    - npm run fetch-sap
  artifacts:
    paths:
      - tmp/xml/
    expire_in: 30 minutes

convert_incidents_job:
  stage: convert
  script:
    - npm run convert-incidents
    - npm run clean-incidents
  artifacts:
    paths:
      - target/incidents-clean.nt
    expire_in: 1 hour

convert_sap_job:
  stage: convert
  tags:
      - large
  script:
    - npm run fetch-carml
    - npm run convert-sap
  artifacts:
    paths:
      - target/sap.ttl
    expire_in: 1 hour

staging_tdb_job:
  stage: staging
  script:
    - npm run tdb-load
    - npm run tdb-query
    - npm run tdb-dump
  artifacts:
    paths:
      - target/everything.nt
    expire_in: 1 day

validate_riot_job:
  stage: validate
  script:
    - npm run validate-riot
  artifacts:
    paths:
      - target/everything.nt
    expire_in: 1 day

post_test_job:
  stage: post
#  only:
#    - tags
#    - develop
  script:
    - npm run bernmobil-lindas-test