image: zazukoians/node-java-jena
before_script:
  - scripts/bootstrap.sh
  - npm install


# stages
stages:
- fetch
- convert
- staging
- validate
- post

# jobs

fetch_incidents_job:
  stage: fetch
  script:
    - npm run fetch-incidents
  artifacts:
    paths:
      - input/incidents.csv
    expire_in: 30 minutes

fetch_sap_job:
  stage: fetch
  script:
    - npm run fetch-sap
  artifacts:
    paths:
      - tmp/xml/
    expire_in: 30 minutes

convert_incidents_job:
  stage: convert
  script:
    - npm run convert-incidents
    - npm run clean-incidents
  artifacts:
    paths:
      - target/incidents-clean.nt
    expire_in: 1 hour

convert_sap_job:
  stage: convert
#  tags:
#      - ssz
  script:
    - npm run fetch-carml
    - npm run convert-sap-zlst
    - npm run convert-sap-zkdr
  artifacts:
    paths:
      - target/sap-zkdr.nt
      - target/sap-zlst.nt
    expire_in: 1 hour

staging_tdb_job:
  stage: staging
  script:
    - npm run tdb-load
    - npm run tdb-query
    - npm run tdb-dump
  artifacts:
    paths:
      - target/everything.nt.gz
    expire_in: 1 day

validate_riot_job:
  stage: validate
  script:
    - npm run validate-riot
  artifacts:
    paths:
      - target/everything.nt.gz
    expire_in: 1 day

post_test_job:
  stage: post
  except:
    - tags
  script:
    - npm run bernmobil-integ-s3

post_prod_job:
  stage: post
  only:
    - tags
  script:
    - npm run bernmobil-prod-s3